// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADfuoUkSKNe9EVTQBpFkVUX8DvRVD4auQ',
    appId: '1:614647581849:web:59e1107fd00137ef8fbc08',
    messagingSenderId: '614647581849',
    projectId: 'myflutterapp-b98cf',
    authDomain: 'myflutterapp-b98cf.firebaseapp.com',
    storageBucket: 'myflutterapp-b98cf.appspot.com',
    measurementId: 'G-M3D53XS36V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy6VwPosQt9N8ruhzo7pAHzK3sfboUYbA',
    appId: '1:614647581849:android:b7e8adb14ce0a5178fbc08',
    messagingSenderId: '614647581849',
    projectId: 'myflutterapp-b98cf',
    storageBucket: 'myflutterapp-b98cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmFmWsTmoI50g1E7BZswl4pmqVFH1KP0',
    appId: '1:614647581849:ios:888bafeecf575cbc8fbc08',
    messagingSenderId: '614647581849',
    projectId: 'myflutterapp-b98cf',
    storageBucket: 'myflutterapp-b98cf.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSmFmWsTmoI50g1E7BZswl4pmqVFH1KP0',
    appId: '1:614647581849:ios:888bafeecf575cbc8fbc08',
    messagingSenderId: '614647581849',
    projectId: 'myflutterapp-b98cf',
    storageBucket: 'myflutterapp-b98cf.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );
}
